# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='个人简介'),
        ),
    ]
