# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
