# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_images', '0002_image_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
